### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Castle1984** [pycasbin/django-authorization-example#3]
After running cmd `python manage.py runserver` , there is an exception:

Watching for file changes with StatReloader
Exception in thread django-main-thread:
File "D:\django-authorization-example\user_management\apps.py", line 31, in ready
    load_policy()
File "D:\django-authorization-example\user_management\apps.py", line 21, in load_policy
    enforcer.add_grouping_policies(g_rules)
TypeError: 'NoneType' object is not subscriptable

How could I solve this problem, I do need your help. Thanks a lot.

**Comment by BustDot** [comment]
Can you provide a more detailed description on how to reproduce this problem? And did this error block the server running? On my mac it doesn't raise error when I start the server with the same command.

**Comment by Castle1984** [comment]
> 
I just change database from sqlite3 to mysql in file /django_example/settings.py. 
And this change I think have nothing to do with this problem.
And then I  run cmd `pip install -r requirements.txt
python manage.py makemigrations
python manage.py migrate
python manage.py runserver` 
So here comes problem:
Also, I don't know where the server is running.
![截图](https://github.com/pycasbin/django-authorization-example/assets/48825393/e4a3c6a8-e288-4016-a68e-3ec014799064)

**Comment by hsluoyz** [comment]
@Castle1984 plz use English in GitHub

**Comment by Castle1984** [comment]
> Can you provide a more detailed description on how to reproduce this problem? And did this error block the server running? On my mac it doesn't raise error when I start the server with the same command.

Do you just use this four command `pip install -r requirements.txt
python manage.py makemigrations
python manage.py migrate
python manage.py runserver` on your mac ? After cloning this project, are there any other commands you have used? If not, I think maybe there are some problems with my code environment。

**Comment by BustDot** [comment]
> > Can you provide a more detailed description on how to reproduce this problem? And did this error block the server running? On my mac it doesn't raise error when I start the server with the same command.
> 
> Do you just use this four command `pip install -r requirements.txt python manage.py makemigrations python manage.py migrate python manage.py runserver` on your mac ? After cloning this project, are there any other commands you have used? If not, I think maybe there are some problems with my code environment。

I just tried with the same command and it can start as normal. You can try to use conda or python virtual env to set up a clean environment.

**Comment by Castle1984** [comment]
After I change a clean environment (also run it on windows), the bug does disappear. 
Thanks a lot.
