### ISSUE TITLE
How casbin works for authentication? I didn't find func enforce()

### ISSUE THREAD

**Issue by Castle1984** [pycasbin/django-authorization-example#4]
I think casbin confirm user permissions using code such as `e.enforcer(request)`.
But I didn't find any code about casbin in [./user_manangement/views.py L37-L58](https://github.com/pycasbin/django-authorization-example/blob/7b8f4e49181a7b51b9abca83557c0bd7e8886724/user_management/views.py#L37-L58) . The code does check user's name and password, and I think this code didn't use casbin to check request for authentication.
Also, only admin can visit 'all_users_profile', but I can't find any code about casbin's function `enforcer`.
I'm curious how it works in this project.  Thanks a lot!

**Comment by Castle1984** [comment]
The problem has been solved, thanks a lot

**Comment by hsluoyz** [comment]
@Castle1984 how is it resolved?

**Comment by Castle1984** [comment]
Thank @BustDot for his patience.
As he said, this project took advantage of [middleware in dauthz](https://github.com/pycasbin/django-authorization/blob/f7151cbe88d5b05e10f2a1cd3bdc5c5f510630b2/dauthz/middlewares/enforcer_middleware.py#L29). This middleware actually also uses function enforcer to check request for authentication.

**Comment by hsluoyz** [comment]
@Castle1984 where did @BustDot say? I didn't see anything..
